# Generated by Django 4.0.4 on 2022-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('base', models.TextField()),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('base', 'target')},
            },
        ),
    ]
